In [1]:
# Importing Libraries 
import pandas as pd
import numpy as np
import seaborn as sns

In [2]:
pd.set_option('display.max_columns', 1000)
pd.set_option('display.max_rows', 1000)

In [3]:
df = pd.read_csv(r"F:\End Project\FinalDatasets\Parking_Violations_Issued_-_Fiscal_Year_2023_20240114.csv" , low_memory=False)

In [4]:
df.shape

(1293558, 43)

In [5]:
df.info('all')

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1293558 entries, 0 to 1293557
Data columns (total 43 columns):
 #   Column                             Non-Null Count    Dtype
---  ------                             --------------    -----
 0   Summons Number                     1293558 non-null  object
 1   Plate ID                           1293533 non-null  object
 2   Registration State                 1293554 non-null  object
 3   Plate Type                         1293554 non-null  object
 4   Issue Date                         1293554 non-null  object
 5   Violation Code                     1293554 non-null  float64
 6   Vehicle Body Type                  1290172 non-null  object
 7   Vehicle Make                       1292195 non-null  object
 8   Issuing Agency                     1293554 non-null  object
 9   Street Code1                       1293554 non-null  float64
 10  Street Code2                       1293554 non-null  float64
 11  Street Code3                       1293554 non-null  float64
 12  Vehicle Expiration Date            1293554 non-null  float64
 13  Violation Location                 783987 non-null   float64
 14  Violation Precinct                 1293554 non-null  float64
 15  Issuer Precinct                    1293554 non-null  float64
 16  Issuer Code                        1293554 non-null  object
 17  Issuer Command                     784847 non-null   object
 18  Issuer Squad                       734733 non-null   object
 19  Violation Time                     1293533 non-null  object
 20  Time First Observed                80260 non-null    object
 21  Violation County                   1289536 non-null  object
 22  Violation In Front Of Or Opposite  775955 non-null   object
 23  House Number                       769838 non-null   object
 24  Street Name                        1293374 non-null  object
 25  Intersecting Street                625127 non-null   object
 26  Date First Observed                1293553 non-null  float64
 27  Law Section                        1293553 non-null  float64
 28  Sub Division                       1293303 non-null  object
 29  Violation Legal Code               508708 non-null   object
 30  Days Parking In Effect             773592 non-null   object
 31  From Hours In Effect               453964 non-null   object
 32  To Hours In Effect                 453964 non-null   object
 33  Vehicle Color                      1204544 non-null  object
 34  Unregistered Vehicle?              32196 non-null    float64
 35  Vehicle Year                       1293553 non-null  float64
 36  Meter Number                       153468 non-null   object
 37  Feet From Curb                     1293553 non-null  float64
 38  Violation Post Code                702539 non-null   object
 39  Violation Description              1261263 non-null  object
 40  No Standing or Stopping Violation  0 non-null        float64
 41  Hydrant Violation                  0 non-null        float64
 42  Double Parking Violation           0 non-null        float64
dtypes: float64(16), object(27)
memory usage: 424.4+ MB

In [6]:
df.describe(include = 'all')

,Summons Number,Plate ID,Registration State,Plate Type,Issue Date,Violation Code,Vehicle Body Type,Vehicle Make,Issuing Agency,Street Code1,Street Code2,Street Code3,Vehicle Expiration Date,Violation Location,Violation Precinct,Issuer Precinct,Issuer Code,Issuer Command,Issuer Squad,Violation Time,Time First Observed,Violation County,Violation In Front Of Or Opposite,House Number,Street Name,Intersecting Street,Date First Observed,Law Section,Sub Division,Violation Legal Code,Days Parking In Effect,From Hours In Effect,To Hours In Effect,Vehicle Color,Unregistered Vehicle?,Vehicle Year,Meter Number,Feet From Curb,Violation Post Code,Violation Description,No Standing or Stopping Violation,Hydrant Violation,Double Parking Violation
count,1293558,1293533,1293554,1293554,1293554,1.293554e+06,1290172,1292195,1293554,1.293554e+06,1.293554e+06,1.293554e+06,1.293554e+06,783987.000000,1.293554e+06,1.293554e+06,1293554,784847,734733,1293533,80260,1289536,775955,769838,1293374,625127,1.293553e+06,1.293553e+06,1293303,508708,773592,453964,453964,1204544,32196.0,1.293553e+06,153468,1.293553e+06,702539,1261263,0.0,0.0,0.0
unique,1293558,778321,65,70,302,NaN,370,835,26,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9998,496,43,1531,1620,15,5,22406,18676,56711,NaN,NaN,116,3,84,85,101,474,NaN,NaN,9540,NaN,373,139,NaN,NaN,NaN
top,1484697303,BLANKPLATE,NY,PAS,06/30/2022,NaN,SUBN,HONDA,T,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,T103,A,0836A,00000,NY,F,N,Broadway,ST,NaN,NaN,B,T,YYYYYYY,0800A,0700P,GY,NaN,NaN,-,NaN,01,PHTO SCHOOL ZN SPEED VIOLATION,NaN,NaN,NaN
freq,1,1478,967931,1059235,64766,NaN,546511,154760,702668,NaN,NaN,NaN,NaN,NaN,NaN,NaN,522456,109014,46319,2956,49934,318205,466979,34630,14404,22842,NaN,NaN,397887,508706,336953,95334,127445,250558,NaN,NaN,32188,NaN,33947,390952,NaN,NaN,NaN
mean,NaN,NaN,NaN,NaN,NaN,3.347853e+01,NaN,NaN,NaN,1.868142e+04,1.577413e+04,1.567268e+04,1.907232e+07,54.940896,3.329814e+01,3.238769e+01,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.210690e+05,7.052556e+02,NaN,NaN,NaN,NaN,NaN,NaN,0.0,1.642059e+03,NaN,6.503947e-02,NaN,NaN,NaN,NaN,NaN
std,NaN,NaN,NaN,NaN,NaN,1.858424e+01,NaN,NaN,NaN,2.233298e+04,2.114037e+04,2.128717e+04,2.576381e+07,38.282847,4.011120e+01,5.480188e+01,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.559950e+06,3.698993e+02,NaN,NaN,NaN,NaN,NaN,NaN,0.0,7.827363e+02,NaN,5.807787e-01,NaN,NaN,NaN,NaN,NaN
min,NaN,NaN,NaN,NaN,NaN,0.000000e+00,NaN,NaN,NaN,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,1.000000,0.000000e+00,0.000000e+00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.000000e+00,0.000000e+00,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.000000e+00,NaN,0.000000e+00,NaN,NaN,NaN,NaN,NaN
25%,NaN,NaN,NaN,NaN,NaN,2.100000e+01,NaN,NaN,NaN,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,19.000000,0.000000e+00,0.000000e+00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.000000e+00,4.080000e+02,NaN,NaN,NaN,NaN,NaN,NaN,0.0,2.006000e+03,NaN,0.000000e+00,NaN,NaN,NaN,NaN,NaN
50%,NaN,NaN,NaN,NaN,NaN,3.600000e+01,NaN,NaN,NaN,1.061000e+04,8.590000e+03,6.940000e+03,2.022089e+07,49.000000,1.400000e+01,9.000000e+00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.000000e+00,4.080000e+02,NaN,NaN,NaN,NaN,NaN,NaN,0.0,2.015000e+03,NaN,0.000000e+00,NaN,NaN,NaN,NaN,NaN
75%,NaN,NaN,NaN,NaN,NaN,3.800000e+01,NaN,NaN,NaN,3.339000e+04,2.589000e+04,2.590800e+04,2.023091e+07,88.000000,6.700000e+01,6.100000e+01,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.000000e+00,1.180000e+03,NaN,NaN,NaN,NaN,NaN,NaN,0.0,2.019000e+03,NaN,0.000000e+00,NaN,NaN,NaN,NaN,NaN
max,NaN,NaN,NaN,NaN,NaN,9.900000e+01,NaN,NaN,NaN,9.791000e+04,9.830000e+04,9.828000e+04,8.888889e+07,807.000000,8.070000e+02,9.970000e+02,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.023070e+07,8.040000e+03,NaN,NaN,NaN,NaN,NaN,NaN,0.0,2.069000e+03,NaN,1.500000e+01,NaN,NaN,NaN,NaN,NaN

In [7]:
df.isnull().sum()

Summons Number                             0
Plate ID                                  25
Registration State                         4
Plate Type                                 4
Issue Date                                 4
Violation Code                             4
Vehicle Body Type                       3386
Vehicle Make                            1363
Issuing Agency                             4
Street Code1                               4
Street Code2                               4
Street Code3                               4
Vehicle Expiration Date                    4
Violation Location                    509571
Violation Precinct                         4
Issuer Precinct                            4
Issuer Code                                4
Issuer Command                        508711
Issuer Squad                          558825
Violation Time                            25
Time First Observed                  1213298
Violation County                        4022
Violation In Front Of Or Opposite     517603
House Number                          523720
Street Name                              184
Intersecting Street                   668431
Date First Observed                        5
Law Section                                5
Sub Division                             255
Violation Legal Code                  784850
Days Parking In Effect                519966
From Hours In Effect                  839594
To Hours In Effect                    839594
Vehicle Color                          89014
Unregistered Vehicle?                1261362
Vehicle Year                               5
Meter Number                         1140090
Feet From Curb                             5
Violation Post Code                   591019
Violation Description                  32295
No Standing or Stopping Violation    1293558
Hydrant Violation                    1293558
Double Parking Violation             1293558
dtype: int64

In [8]:
df.head()

,Summons Number,Plate ID,Registration State,Plate Type,Issue Date,Violation Code,Vehicle Body Type,Vehicle Make,Issuing Agency,Street Code1,Street Code2,Street Code3,Vehicle Expiration Date,Violation Location,Violation Precinct,Issuer Precinct,Issuer Code,Issuer Command,Issuer Squad,Violation Time,Time First Observed,Violation County,Violation In Front Of Or Opposite,House Number,Street Name,Intersecting Street,Date First Observed,Law Section,Sub Division,Violation Legal Code,Days Parking In Effect,From Hours In Effect,To Hours In Effect,Vehicle Color,Unregistered Vehicle?,Vehicle Year,Meter Number,Feet From Curb,Violation Post Code,Violation Description,No Standing or Stopping Violation,Hydrant Violation,Double Parking Violation
0,1484697303,JER1863,NY,PAS,06/10/2022,67.0,SDN,TOYOT,P,34330.0,179.0,0.0,20221210.0,10.0,10.0,1.0,160195,0001,0000,1037A,NaN,NY,F,NaN,W 28TH ST,CHELSEA PK,0.0,408.0,E3,NaN,BBBBBBB,ALL,ALL,BLK,0.0,2004.0,-,0.0,NaN,NaN,NaN,NaN,NaN
1,1484697315,KEV4487,NY,PAS,06/13/2022,51.0,SUBN,JEEP,K,34310.0,16400.0,11010.0,20220908.0,10.0,10.0,1.0,160195,0001,0000,1045A,NaN,NY,O,436,27TH DR,NaN,0.0,408.0,F3,NaN,BBBBBBB,ALL,ALL,GRAY,0.0,2017.0,-,0.0,NaN,NaN,NaN,NaN,NaN
2,1484697625,H73NYD,NJ,PAS,06/19/2022,63.0,SDN,JEEP,N,30640.0,13015.0,28540.0,0.0,1.0,1.0,1.0,161315,0001,0000,1116A,NaN,NY,NaN,109,SOUTH ST,NaN,0.0,408.0,F3,NaN,BBBBBBB,ALL,ALL,GRAY,0.0,0.0,-,0.0,NaN,NaN,NaN,NaN,NaN
3,1484697674,GJC9296,NY,PAS,06/19/2022,63.0,SUBN,LEXUS,N,30640.0,13015.0,28540.0,20230820.0,1.0,1.0,1.0,161315,0001,0000,1052A,NaN,NY,NaN,109,SOUTH ST,NaN,0.0,408.0,F3,NaN,BBBBBBB,ALL,ALL,NaN,0.0,0.0,-,0.0,NaN,NaN,NaN,NaN,NaN
4,1484697686,M51PUV,NJ,PAS,06/19/2022,63.0,SDN,HYUND,N,30640.0,13015.0,28540.0,0.0,1.0,1.0,1.0,161315,0001,0000,1107A,NaN,NY,NaN,109,SOUTH ST,NaN,0.0,408.0,F3,NaN,BBBBBBB,ALL,ALL,BLUE,0.0,0.0,-,0.0,NaN,NaN,NaN,NaN,NaN

In [9]:
df.tail()

,Summons Number,Plate ID,Registration State,Plate Type,Issue Date,Violation Code,Vehicle Body Type,Vehicle Make,Issuing Agency,Street Code1,Street Code2,Street Code3,Vehicle Expiration Date,Violation Location,Violation Precinct,Issuer Precinct,Issuer Code,Issuer Command,Issuer Squad,Violation Time,Time First Observed,Violation County,Violation In Front Of Or Opposite,House Number,Street Name,Intersecting Street,Date First Observed,Law Section,Sub Division,Violation Legal Code,Days Parking In Effect,From Hours In Effect,To Hours In Effect,Vehicle Color,Unregistered Vehicle?,Vehicle Year,Meter Number,Feet From Curb,Violation Post Code,Violation Description,No Standing or Stopping Violation,Hydrant Violation,Double Parking Violation
1293553,9002562615,UCA2019,VA,PAS,07/26/2022,21.0,SUBN,AUDI,T,5580.0,10680.0,10730.0,20220788.0,68.0,68.0,68.0,{,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1293554,"""error"" : true",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1293555,"""message"" : ""Internal error""",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1293556,"""status"" : 500",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1293557,},NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [10]:
df.columns

Index(['Summons Number', 'Plate ID', 'Registration State', 'Plate Type',
       'Issue Date', 'Violation Code', 'Vehicle Body Type', 'Vehicle Make',
       'Issuing Agency', 'Street Code1', 'Street Code2', 'Street Code3',
       'Vehicle Expiration Date', 'Violation Location', 'Violation Precinct',
       'Issuer Precinct', 'Issuer Code', 'Issuer Command', 'Issuer Squad',
       'Violation Time', 'Time First Observed', 'Violation County',
       'Violation In Front Of Or Opposite', 'House Number', 'Street Name',
       'Intersecting Street', 'Date First Observed', 'Law Section',
       'Sub Division', 'Violation Legal Code', 'Days Parking In Effect',
       'From Hours In Effect', 'To Hours In Effect', 'Vehicle Color',
       'Unregistered Vehicle?', 'Vehicle Year', 'Meter Number',
       'Feet From Curb', 'Violation Post Code', 'Violation Description',
       'No Standing or Stopping Violation', 'Hydrant Violation',
       'Double Parking Violation'],
      dtype='object')

In [11]:
df.ndim

2

In [12]:
df.duplicated().sum()

0

In [13]:
df.corr(numeric_only = True)

,Violation Code,Street Code1,Street Code2,Street Code3,Vehicle Expiration Date,Violation Location,Violation Precinct,Issuer Precinct,Date First Observed,Law Section,Unregistered Vehicle?,Vehicle Year,Feet From Curb,No Standing or Stopping Violation,Hydrant Violation,Double Parking Violation
Violation Code,1.000000,0.106075,0.099190,0.105610,0.079977,0.071448,0.173111,0.151492,0.007295,-0.166972,NaN,0.016148,0.039298,NaN,NaN,NaN
Street Code1,0.106075,1.000000,0.546427,0.556496,0.360939,0.183497,0.542964,0.376011,0.024054,-0.657584,NaN,-0.249929,0.054293,NaN,NaN,NaN
Street Code2,0.099190,0.546427,1.000000,0.742235,0.258708,0.154680,0.436721,0.300166,0.021311,-0.510914,NaN,-0.190058,0.026669,NaN,NaN,NaN
Street Code3,0.105610,0.556496,0.742235,1.000000,0.273113,0.158912,0.451702,0.306584,0.023212,-0.529590,NaN,-0.194568,0.029549,NaN,NaN,NaN
Vehicle Expiration Date,0.079977,0.360939,0.258708,0.273113,1.000000,-0.178309,0.292578,0.221318,0.039377,-0.595118,NaN,-0.541514,0.055786,NaN,NaN,NaN
Violation Location,0.071448,0.183497,0.154680,0.158912,-0.178309,1.000000,1.000000,0.581231,-0.041880,-0.001451,NaN,0.096018,0.007939,NaN,NaN,NaN
Violation Precinct,0.173111,0.542964,0.436721,0.451702,0.292578,1.000000,1.000000,0.696723,0.010468,-0.667262,NaN,-0.184829,0.066275,NaN,NaN,NaN
Issuer Precinct,0.151492,0.376011,0.300166,0.306584,0.221318,0.581231,0.696723,1.000000,0.034052,-0.474850,NaN,-0.117222,0.053246,NaN,NaN,NaN
Date First Observed,0.007295,0.024054,0.021311,0.023212,0.039377,-0.041880,0.010468,0.034052,1.000000,-0.062369,NaN,-0.031345,-0.007415,NaN,NaN,NaN
Law Section,-0.166972,-0.657584,-0.510914,-0.529590,-0.595118,-0.001451,-0.667262,-0.474850,-0.062369,1.000000,NaN,0.374709,-0.089994,NaN,NaN,NaN
Unregistered Vehicle?,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Vehicle Year,0.016148,-0.249929,-0.190058,-0.194568,-0.541514,0.096018,-0.184829,-0.117222,-0.031345,0.374709,NaN,1.000000,-0.055611,NaN,NaN,NaN
Feet From Curb,0.039298,0.054293,0.026669,0.029549,0.055786,0.007939,0.066275,0.053246,-0.007415,-0.089994,NaN,-0.055611,1.000000,NaN,NaN,NaN
No Standing or Stopping Violation,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Hydrant Violation,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Double Parking Violation,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [14]:
# Delete Columns with NULL values having thresold below
threshold = len(df)*0.80
df = df.dropna(axis=1, thresh=threshold)

In [15]:
df.shape

(1293558, 26)

In [16]:
df.columns

Index(['Summons Number', 'Plate ID', 'Registration State', 'Plate Type',
       'Issue Date', 'Violation Code', 'Vehicle Body Type', 'Vehicle Make',
       'Issuing Agency', 'Street Code1', 'Street Code2', 'Street Code3',
       'Vehicle Expiration Date', 'Violation Precinct', 'Issuer Precinct',
       'Issuer Code', 'Violation Time', 'Violation County', 'Street Name',
       'Date First Observed', 'Law Section', 'Sub Division', 'Vehicle Color',
       'Vehicle Year', 'Feet From Curb', 'Violation Description'],
      dtype='object')

In [17]:
# Trim whitespace from column names
df.columns = df.columns.str.strip()

In [18]:
df['Violation Precinct'].isnull().sum()

4

In [19]:
df.head(2)

,Summons Number,Plate ID,Registration State,Plate Type,Issue Date,Violation Code,Vehicle Body Type,Vehicle Make,Issuing Agency,Street Code1,Street Code2,Street Code3,Vehicle Expiration Date,Violation Precinct,Issuer Precinct,Issuer Code,Violation Time,Violation County,Street Name,Date First Observed,Law Section,Sub Division,Vehicle Color,Vehicle Year,Feet From Curb,Violation Description
0,1484697303,JER1863,NY,PAS,06/10/2022,67.0,SDN,TOYOT,P,34330.0,179.0,0.0,20221210.0,10.0,1.0,160195,1037A,NY,W 28TH ST,0.0,408.0,E3,BLK,2004.0,0.0,NaN
1,1484697315,KEV4487,NY,PAS,06/13/2022,51.0,SUBN,JEEP,K,34310.0,16400.0,11010.0,20220908.0,10.0,1.0,160195,1045A,NY,27TH DR,0.0,408.0,F3,GRAY,2017.0,0.0,NaN

In [20]:
df.isnull().sum()

Summons Number                 0
Plate ID                      25
Registration State             4
Plate Type                     4
Issue Date                     4
Violation Code                 4
Vehicle Body Type           3386
Vehicle Make                1363
Issuing Agency                 4
Street Code1                   4
Street Code2                   4
Street Code3                   4
Vehicle Expiration Date        4
Violation Precinct             4
Issuer Precinct                4
Issuer Code                    4
Violation Time                25
Violation County            4022
Street Name                  184
Date First Observed            5
Law Section                    5
Sub Division                 255
Vehicle Color              89014
Vehicle Year                   5
Feet From Curb                 5
Violation Description      32295
dtype: int64

In [21]:
df.shape

(1293558, 26)

In [22]:
# Iterate over columns
for col in df.columns:
    # Check if the column has less than 10000 null values
    if df[col].isnull().sum() < 10000:
        # Drop null rows from that column
        df = df.dropna(subset=[col])

# Now df contains rows with null values dropped from columns with less than 10000 null values

In [23]:
df.isnull().sum()

Summons Number                 0
Plate ID                       0
Registration State             0
Plate Type                     0
Issue Date                     0
Violation Code                 0
Vehicle Body Type              0
Vehicle Make                   0
Issuing Agency                 0
Street Code1                   0
Street Code2                   0
Street Code3                   0
Vehicle Expiration Date        0
Violation Precinct             0
Issuer Precinct                0
Issuer Code                    0
Violation Time                 0
Violation County               0
Street Name                    0
Date First Observed            0
Law Section                    0
Sub Division                   0
Vehicle Color              87014
Vehicle Year                   0
Feet From Curb                 0
Violation Description      26520
dtype: int64

In [24]:
df['Vehicle Color'].describe()

count     1198557
unique        452
top            GY
freq       250105
Name: Vehicle Color, dtype: object

In [25]:
df['Violation Description'].describe()

count                            1259051
unique                               137
top       PHTO SCHOOL ZN SPEED VIOLATION
freq                              389882
Name: Violation Description, dtype: object

In [26]:
df.loc[:, 'Vehicle Color'] = df['Vehicle Color'].fillna(df['Vehicle Color'].mode().iloc[0])
df.loc[:, 'Violation Description'] = df['Violation Description'].fillna(df['Violation Description'].mode().iloc[0])

In [27]:
df.isnull().sum()

Summons Number             0
Plate ID                   0
Registration State         0
Plate Type                 0
Issue Date                 0
Violation Code             0
Vehicle Body Type          0
Vehicle Make               0
Issuing Agency             0
Street Code1               0
Street Code2               0
Street Code3               0
Vehicle Expiration Date    0
Violation Precinct         0
Issuer Precinct            0
Issuer Code                0
Violation Time             0
Violation County           0
Street Name                0
Date First Observed        0
Law Section                0
Sub Division               0
Vehicle Color              0
Vehicle Year               0
Feet From Curb             0
Violation Description      0
dtype: int64

In [28]:
df['Violation Description'].value_counts().head(50)

Violation Description
PHTO SCHOOL ZN SPEED VIOLATION    416402
21-No Parking (street clean)      141232
38-Failure to Dsplay Meter Rec     79791
14-No Standing                     66651
FAILURE TO STOP AT RED LIGHT       59169
BUS LANE VIOLATION                 52742
40-Fire Hydrant                    48889
No Parking Street Cleaning         45254
71A-Insp Sticker Expired (NYS)     44420
20A-No Parking (Non-COM)           41274
70A-Reg. Sticker Expired (NYS)     29811
31-No Stand (Com. Mtr. Zone)       21121
19-No Stand (bus stop)             20713
37-Expired Parking Meter           19733
69-Fail to Dsp Prking Mtr Rcpt     18954
20-No Parking (Com Plate)          17315
16A-No Std (Com Veh) Non-COM       15792
46A-Double Parking (Non-COM)       14080
74A-Improperly Displayed Plate     10095
74-Missing Display Plate            9767
46B-Double Parking (Com-100Ft)      9114
47-Double PKG-Midtown(Com Veh)      8595
71-Insp. Sticker Missing (NYS       8070
17-No Stand (exc auth veh)          7913
10-No Stopping                      6840
50-Crosswalk                        6561
84-Platform lifts in low posit      6344
MOBILE BUS LANE VIOLATION           5005
48-Bike Lane                        4990
70-Reg. Sticker Missing (NYS)       4250
16-No Std (Com Veh) Com Plate       3811
53-Safety Zone                      3409
51-Sidewalk                         3283
78-Nighttime PKG on Res Street      2821
42-Exp Meter (Com Zone)             2738
18-No Stand (bus lane)              2593
82-Unaltered Commerc Vehicle        2384
13-No Stand (taxi stand)            1783
70B-Impropr Dsply of Reg (NYS)      1720
68-Not Pkg. Comp. w Psted Sign      1665
74B-Covered Plate                   1577
75-No Match-Plate/Reg. Sticker      1267
61-Wrong Way                        1116
Detached Trailer                     952
09-Blocking the Box                  888
66-Detached Trailer                  819
22A-No St Taxi/FHV Rlf-NO TAXI       792
64-No STD Ex Con/DPL, D/S Dec        693
No Standing                          689
72-Insp Stkr Mutilated               598
Name: count, dtype: int64

In [29]:
df.head(1)

,Summons Number,Plate ID,Registration State,Plate Type,Issue Date,Violation Code,Vehicle Body Type,Vehicle Make,Issuing Agency,Street Code1,Street Code2,Street Code3,Vehicle Expiration Date,Violation Precinct,Issuer Precinct,Issuer Code,Violation Time,Violation County,Street Name,Date First Observed,Law Section,Sub Division,Vehicle Color,Vehicle Year,Feet From Curb,Violation Description
0,1484697303,JER1863,NY,PAS,06/10/2022,67.0,SDN,TOYOT,P,34330.0,179.0,0.0,20221210.0,10.0,1.0,160195,1037A,NY,W 28TH ST,0.0,408.0,E3,BLK,2004.0,0.0,PHTO SCHOOL ZN SPEED VIOLATION

In [30]:
df['Violation Time'] = df['Violation Time'] + 'M'

In [31]:
df.head(1)

,Summons Number,Plate ID,Registration State,Plate Type,Issue Date,Violation Code,Vehicle Body Type,Vehicle Make,Issuing Agency,Street Code1,Street Code2,Street Code3,Vehicle Expiration Date,Violation Precinct,Issuer Precinct,Issuer Code,Violation Time,Violation County,Street Name,Date First Observed,Law Section,Sub Division,Vehicle Color,Vehicle Year,Feet From Curb,Violation Description
0,1484697303,JER1863,NY,PAS,06/10/2022,67.0,SDN,TOYOT,P,34330.0,179.0,0.0,20221210.0,10.0,1.0,160195,1037AM,NY,W 28TH ST,0.0,408.0,E3,BLK,2004.0,0.0,PHTO SCHOOL ZN SPEED VIOLATION

In [32]:
df['Violation Time'].nunique

<bound method IndexOpsMixin.nunique of 0          1037AM
1          1045AM
2          1116AM
3          1052AM
4          1107AM
            ...
1293548    0732AM
1293549    0734AM
1293550    0737AM
1293551    0741AM
1293552    0743AM
Name: Violation Time, Length: 1285571, dtype: object>

In [33]:
# Convert the time column to 'hh:mm AM/PM' format
df['Violation Time'] = df['Violation Time'].str[:2] + ':' + df['Violation Time'].str[2:4] + ' ' + df['Violation Time'].str[4:]

In [34]:
df['Violation Time'].head(10)

0     10:37 AM
1     10:45 AM
2     11:16 AM
3     10:52 AM
4     11:07 AM
7     12:05 PM
8     05:35 PM
9     03:07 PM
10    02:25 PM
11    03:20 PM
Name: Violation Time, dtype: object

In [35]:
# Convert 'Time' column to datetime format
# df['Violation Time'] = pd.to_datetime(df['Violation Time']).dt.time

In [36]:
df['Plate Type'].unique()

array(['PAS', 'OMS', '999', 'OMT', 'SRF', 'COM', 'MED', 'ORG', 'MOT',
       'TRL', 'HIS', 'SPO', 'MCL', 'NYS', 'RGL', 'VPL', 'OMV', 'OML',
       'VAS', 'HIR', 'PSD', 'HAM', 'TOW', 'SOS', 'PHS', 'JSC', 'ITP',
       'CMB', 'AGC', 'NLM', 'NYC', 'CSP', 'TRC', 'OMR', 'SEM', 'APP',
       'SRN', 'LMB', 'SCL', 'IRP', 'DLR', 'NYA', 'CHC', 'STA', 'TRA',
       'LTR', 'RGC', 'ORC', 'ARG', 'SPC', 'LMA', 'SUP', 'ATV', 'AYG',
       'AMB', 'BOB', 'AGR', 'STG', 'CLG', 'CME', 'LMC', 'OMO', 'FAR',
       'CBS', 'JCA', 'MCD', 'CCK', 'CMH', 'PPH'], dtype=object)

In [37]:
len(df[df['Plate Type']=='999'])
# Checking the length of Plate Type '999' ,

5559

In [38]:
df = df[df['Plate Type'] != '999']

In [39]:
df['Plate Type'].unique()

array(['PAS', 'OMS', 'OMT', 'SRF', 'COM', 'MED', 'ORG', 'MOT', 'TRL',
       'HIS', 'SPO', 'MCL', 'NYS', 'RGL', 'VPL', 'OMV', 'OML', 'VAS',
       'HIR', 'PSD', 'HAM', 'TOW', 'SOS', 'PHS', 'JSC', 'ITP', 'CMB',
       'AGC', 'NLM', 'NYC', 'CSP', 'TRC', 'OMR', 'SEM', 'APP', 'SRN',
       'LMB', 'SCL', 'IRP', 'DLR', 'NYA', 'CHC', 'STA', 'TRA', 'LTR',
       'RGC', 'ORC', 'ARG', 'SPC', 'LMA', 'SUP', 'ATV', 'AYG', 'AMB',
       'BOB', 'AGR', 'STG', 'CLG', 'CME', 'LMC', 'OMO', 'FAR', 'CBS',
       'JCA', 'MCD', 'CCK', 'CMH', 'PPH'], dtype=object)

In [40]:
df['Plate Type'].value_counts()

Plate Type
PAS    1052435
COM     129418
OMT      43192
SRF      14726
OMS      12280
APP       4440
MOT       3804
LMB       3273
ORG       2828
SPO       1988
MED       1697
TRC       1510
OMR       1134
CMB       1120
PSD        936
SCL        737
RGL        719
TOW        529
OML        452
VAS        436
ITP        435
TRL        296
IRP        253
SRN        237
DLR        195
HIS        165
MCL        108
TRA         88
NYC         63
STA         62
AMB         56
ORC         50
PHS         46
SPC         37
AGR         32
NYS         28
OMV         27
LMA         19
CHC         17
SOS         14
HAM         13
AYG         11
ATV         11
CSP         11
BOB         10
RGC         10
STG          8
NLM          7
CBS          6
MCD          5
SUP          5
CMH          4
LTR          4
AGC          3
SEM          3
ARG          3
VPL          2
NYA          2
HIR          2
PPH          2
JSC          1
CLG          1
CME          1
LMC          1
OMO          1
FAR          1
JCA          1
CCK          1
Name: count, dtype: int64

In [41]:
df['Registration State'].value_counts()

Registration State
NY    962449
NJ    112949
PA     42000
FL     29643
CT     19987
IN     11376
GA     10080
TX      9251
VA      9026
MA      8441
NC      7855
MD      7483
CA      5412
IL      4154
AZ      4012
OH      3997
SC      3248
ME      2685
DE      2190
TN      1848
AL      1810
MN      1704
MI      1618
WA      1547
VT      1406
RI      1272
NH      1140
OK       978
CO       840
WI       820
MS       780
MO       736
OR       665
ON       646
99       633
KY       580
LA       474
WV       427
QB       407
SD       405
DC       396
AR       358
NV       301
MT       260
IA       231
UT       201
NM       190
GV       181
KS       173
NE       165
DP       137
ID       120
WY        67
ND        59
AK        53
HI        45
PR        35
NS        21
AB        15
NB        14
BC         9
MB         3
PE         2
SK         1
FO         1
Name: count, dtype: int64

In [42]:
df['Issue Date'].unique()

array(['06/10/2022', '06/13/2022', '06/19/2022', '06/20/2022',
       '06/25/2022', '06/05/2022', '06/19/2023', '06/09/2022',
       '06/30/2022', '07/03/2022', '06/18/2022', '06/29/2022',
       '07/04/2022', '07/09/2022', '06/15/2022', '06/11/2022',
       '06/17/2022', '06/04/2022', '07/05/2022', '06/26/2022',
       '06/06/2022', '06/08/2022', '06/22/2022', '07/02/2022',
       '06/14/2022', '06/23/2022', '06/24/2022', '06/27/2022',
       '06/21/2022', '06/12/2022', '07/10/2022', '07/06/2022',
       '07/07/2022', '04/29/2022', '05/28/2022', '06/02/2022',
       '06/01/2022', '07/01/2022', '06/16/2022', '05/11/2022',
       '04/01/2022', '05/29/2022', '05/03/2022', '06/20/2021',
       '06/28/2022', '06/03/2022', '05/05/2022', '07/08/2022',
       '06/07/2022', '05/22/2022', '05/13/2022', '07/11/2022',
       '06/25/2021', '07/12/2022', '05/30/2022', '05/31/2022',
       '06/23/2021', '04/21/2022', '03/15/2022', '02/07/2022',
       '06/20/2023', '03/27/2024', '05/26/2022', '05/14/2022',
       '05/18/2022', '05/20/2022', '05/19/2022', '05/10/2022',
       '05/12/2022', '05/23/2022', '05/27/2022', '03/01/2022',
       '03/30/2022', '05/02/2022', '05/04/2022', '04/18/2022',
       '04/19/2022', '04/26/2022', '04/04/2022', '04/12/2022',
       '04/15/2022', '02/25/2022', '03/24/2022', '03/28/2022',
       '03/31/2022', '03/07/2022', '09/08/2021', '07/25/2022',
       '05/17/2022', '04/06/2022', '03/29/2022', '06/10/2021',
       '05/08/2022', '06/13/2021', '04/13/2022', '10/17/2022',
       '07/05/2021', '06/17/2021', '06/24/2020', '06/22/2023',
       '07/22/2022', '06/27/2023', '06/26/2021', '05/23/2023',
       '06/25/2023', '07/13/2022', '06/12/2014', '05/06/2022',
       '05/24/2022', '05/25/2022', '06/23/2023', '07/03/2023',
       '07/03/2021', '04/03/2022', '06/18/2023', '06/28/2000',
       '06/19/2025', '05/15/2022', '06/28/2020', '07/02/2021',
       '07/04/2021', '07/15/2022', '07/01/2023', '07/06/2023',
       '12/14/2021', '05/01/2022', '01/22/2022', '07/03/2020',
       '07/05/2023', '06/16/2021', '06/25/2020', '06/17/2023',
       '06/24/2023', '03/09/2022', '06/16/2020', '01/07/2022',
       '04/23/2022', '06/24/2021', '07/08/2023', '06/22/2020',
       '07/12/2023', '07/09/2000', '06/26/2026', '07/09/2023',
       '06/24/2012', '07/14/2023', '07/18/2022', '07/27/2022',
       '06/28/2021', '07/30/2022', '07/01/2027', '05/30/2021',
       '05/16/2022', '06/22/2021', '05/21/2022', '06/05/2023',
       '06/15/2023', '07/19/2022', '07/20/2022', '07/14/2022',
       '07/04/2020', '07/17/2022', '02/21/2022', '07/21/2022',
       '07/16/2022', '07/23/2022', '06/11/2021', '07/26/2022',
       '06/05/2021', '06/01/2023', '10/31/2021', '12/17/2021',
       '04/02/2022', '04/30/2022', '07/24/2022', '08/06/2022',
       '08/03/2022', '07/28/2022', '08/04/2022', '07/31/2022',
       '08/07/2022', '08/14/2022', '08/13/2022', '08/11/2022',
       '07/29/2022', '08/05/2022', '08/02/2022', '08/01/2022',
       '08/10/2022', '08/12/2022', '03/21/2022', '08/06/2021',
       '03/17/2022', '04/17/2022', '08/01/2021', '06/29/2020',
       '06/18/2021', '03/02/2022', '10/11/2021', '06/29/2023',
       '06/15/2021', '06/16/2023', '06/14/2021', '07/10/2021',
       '02/16/2022', '06/08/2021', '10/15/2022', '04/08/2022',
       '11/13/2022', '06/30/2021', '06/11/2023', '03/23/2022',
       '07/09/2027', '03/16/2022', '03/06/2022', '03/19/2022',
       '10/26/2022', '03/10/2022', '03/14/2022', '03/22/2022',
       '03/27/2022', '02/20/2022', '02/13/2022', '12/30/2021',
       '10/29/2022', '06/17/2027', '10/09/2022', '01/15/2022',
       '06/20/2020', '10/28/2022', '11/28/2022', '03/08/2022',
       '03/18/2022', '04/07/2022', '04/20/2022', '04/14/2022',
       '06/29/2027', '09/29/2022', '01/11/2022', '07/02/2023',
       '10/21/2021', '05/09/2022', '07/07/2023', '06/21/2020',
       '06/25/2025', '04/27/2022', '03/13/2022', '02/28/2022',
       '06/14/2023', '06/15/2027', '12/01/2021', '09/12/2022',
       '07/17/2023', '06/19/2021', '06/14/2020', '06/10/2018',
       '07/11/2021', '07/08/2020', '06/19/2027', '08/09/2022',
       '07/14/2021', '06/28/2031', '08/27/2022', '06/19/2020',
       '06/13/2023', '11/23/2022', '07/18/2023', '07/07/2049',
       '06/24/2066', '11/11/2022', '06/27/2021', '07/25/2023',
       '09/24/2021', '08/08/2022', '07/06/2021', '08/01/2000'],
      dtype=object)

In [43]:
df['Issue Date'] = pd.to_datetime(df['Issue Date'])
df_sorted = df.sort_values(by = 'Issue Date')

In [44]:
df_sorted.head()

,Summons Number,Plate ID,Registration State,Plate Type,Issue Date,Violation Code,Vehicle Body Type,Vehicle Make,Issuing Agency,Street Code1,Street Code2,Street Code3,Vehicle Expiration Date,Violation Precinct,Issuer Precinct,Issuer Code,Violation Time,Violation County,Street Name,Date First Observed,Law Section,Sub Division,Vehicle Color,Vehicle Year,Feet From Curb,Violation Description
3873,1486052228,KXFB52,FL,PAS,2000-06-28,99.0,SDN,KIA,P,6140.0,21540.0,21590.0,0.0,109.0,109.0,963483,12:06 AM,Q,15 AVE,0.0,408.0,J5,BLACK,0.0,0.0,PHTO SCHOOL ZN SPEED VIOLATION
7040,1487623604,KKP7984,NY,PAS,2000-07-09,40.0,SDN,TOYOT,P,40090.0,11090.0,54890.0,20230404.0,110.0,110.0,949429,10:06 PM,Q,CORONA AVE,0.0,408.0,F2,WHITE,2021.0,0.0,PHTO SCHOOL ZN SPEED VIOLATION
1174358,1472943545,KXU6330,NY,PAS,2000-08-01,98.0,SDN,HONDA,P,68954.0,68942.0,14230.0,20240618.0,69.0,69.0,956187,09:25 AM,K,PAERDEGAT 10 ST,0.0,408.0,F1,BLACK,2019.0,0.0,PHTO SCHOOL ZN SPEED VIOLATION
8505,1487960633,KVT4495,NY,PAS,2012-06-24,46.0,SUBN,ACURA,P,37240.0,11710.0,12010.0,0.0,33.0,33.0,961824,09:13 PM,NY,WEST 174 STREET,0.0,408.0,F1,GRY,0.0,0.0,PHTO SCHOOL ZN SPEED VIOLATION
3060,1476136660,GZE2213,NY,PAS,2014-06-12,17.0,SDN,CADIL,P,34830.0,11010.0,11110.0,20230720.0,0.0,420.0,939880,08:41 AM,NY,W 53RD,0.0,408.0,C4,GY,0.0,0.0,PHTO SCHOOL ZN SPEED VIOLATION

In [45]:
df_sorted.tail()

,Summons Number,Plate ID,Registration State,Plate Type,Issue Date,Violation Code,Vehicle Body Type,Vehicle Make,Issuing Agency,Street Code1,Street Code2,Street Code3,Vehicle Expiration Date,Violation Precinct,Issuer Precinct,Issuer Code,Violation Time,Violation County,Street Name,Date First Observed,Law Section,Sub Division,Vehicle Color,Vehicle Year,Feet From Curb,Violation Description
9219,1488079420,KUW3249,NY,PAS,2027-07-01,98.0,SDN,FORD,P,22040.0,20240.0,20440.0,20240221.0,106.0,106.0,960187,04:39 PM,Q,132 ST,0.0,408.0,F2,BLK,2016.0,0.0,PHTO SCHOOL ZN SPEED VIOLATION
396764,1452057631,J10PTN,NJ,PAS,2027-07-09,99.0,SUBN,GMC,N,13930.0,0.0,0.0,20230320.0,30.0,982.0,600173,04:14 PM,NY,RIVERBANK STATE PARK,0.0,408.0,99,GY,2011.0,0.0,PHTO SCHOOL ZN SPEED VIOLATION
425306,1488411190,T800334C,NY,OMT,2031-06-28,40.0,SDN,NISSA,P,59830.0,45430.0,38730.0,20220131.0,75.0,75.0,972279,06:06 AM,K,MCKINLEY AVE,0.0,408.0,E3,SILVE,2018.0,0.0,PHTO SCHOOL ZN SPEED VIOLATION
435356,1487877730,42687C8,TX,PAS,2049-07-07,40.0,SDN,CHEVR,P,72620.0,47520.0,57720.0,20220413.0,49.0,49.0,968795,09:30 AM,BX,WALLACE AVE,0.0,408.0,D1,BLUE,2017.0,0.0,PHTO SCHOOL ZN SPEED VIOLATION
435392,1487879672,2BA285,SD,PAS,2066-06-24,14.0,SUBN,FORD,P,9320.0,10420.0,55520.0,20220228.0,49.0,49.0,947691,03:50 AM,BX,ARNOW AVE,0.0,408.0,E2,WH,0.0,0.0,PHTO SCHOOL ZN SPEED VIOLATION

In [46]:
# df['Issue Date'] = pd.to_datetime(df['Issue Date'])
df['Issue Year'] = df['Issue Date'].dt.year
df['Issue Month'] = df['Issue Date'].dt.month

In [47]:
df.head(1)

,Summons Number,Plate ID,Registration State,Plate Type,Issue Date,Violation Code,Vehicle Body Type,Vehicle Make,Issuing Agency,Street Code1,Street Code2,Street Code3,Vehicle Expiration Date,Violation Precinct,Issuer Precinct,Issuer Code,Violation Time,Violation County,Street Name,Date First Observed,Law Section,Sub Division,Vehicle Color,Vehicle Year,Feet From Curb,Violation Description,Issue Year,Issue Month
0,1484697303,JER1863,NY,PAS,2022-06-10,67.0,SDN,TOYOT,P,34330.0,179.0,0.0,20221210.0,10.0,1.0,160195,10:37 AM,NY,W 28TH ST,0.0,408.0,E3,BLK,2004.0,0.0,PHTO SCHOOL ZN SPEED VIOLATION,2022,6

In [48]:
df['Issue Year'].max() , '&' , df['Issue Year'].min()

(2066, '&', 2000)

In [49]:
df['Issue Year'].value_counts()

Issue Year
2022    1279863
2021         61
2023         55
2020         14
2027          6
2000          3
2025          2
2024          1
2014          1
2026          1
2012          1
2018          1
2031          1
2049          1
2066          1
Name: count, dtype: int64

In [50]:
# Filter rows where 'Issue Year' is between 2020 and 2024
df = df[(df['Issue Year'] >= 2020) & (df['Issue Year'] <= 2024)]

In [51]:
df['Issue Year'].value_counts()

Issue Year
2022    1279863
2021         61
2023         55
2020         14
2024          1
Name: count, dtype: int64

In [52]:
df['Issue Month'].value_counts()

Issue Month
7     981794
6     297150
5        666
4        165
8        119
3         64
10        11
2          9
9          4
12         4
1          4
11         4
Name: count, dtype: int64

In [53]:
df[df['Issue Year']==2020]['Issue Month'].value_counts().sort_index()

Issue Month
6    11
7     3
Name: count, dtype: int64

In [54]:
# df.groupby(['Issue Month']).count()['Issue Year'].sort_values(ascending=False).reset_index().head(5)

In [55]:
# df[df['Issue Year']==2020]['Issue Month']==6

In [56]:
df.columns

Index(['Summons Number', 'Plate ID', 'Registration State', 'Plate Type',
       'Issue Date', 'Violation Code', 'Vehicle Body Type', 'Vehicle Make',
       'Issuing Agency', 'Street Code1', 'Street Code2', 'Street Code3',
       'Vehicle Expiration Date', 'Violation Precinct', 'Issuer Precinct',
       'Issuer Code', 'Violation Time', 'Violation County', 'Street Name',
       'Date First Observed', 'Law Section', 'Sub Division', 'Vehicle Color',
       'Vehicle Year', 'Feet From Curb', 'Violation Description', 'Issue Year',
       'Issue Month'],
      dtype='object')

In [57]:
kk = df['Violation Time'].str[:2].astype(int)

In [58]:
# Filter values between 1 and 12
df = df[(kk >= 1) & (kk <= 12)]

In [59]:
df['Violation Code'].nunique()

89

In [60]:
df['Violation Code'].unique()

array([67., 51., 63., 98., 10., 45., 14., 20., 68., 27., 53., 19., 40.,
       74., 16., 17., 48., 62., 70., 46., 50., 71., 21., 24., 41., 99.,
       75., 83., 18., 37., 38., 78., 97., 61., 91., 96., 52., 13., 11.,
       39., 54., 49.,  5., 31., 60., 90., 95.,  6., 92., 89., 85., 55.,
       56.,  9., 66., 80., 36., 72., 22., 26.,  7., 69., 12., 87., 33.,
       73., 76., 79., 82., 64., 25.,  4., 47., 42., 35., 84., 32.,  8.,
       77., 58., 23., 65., 34., 57., 81., 44., 59.,  1., 29.])

In [61]:
df['Violation Time'] = pd.to_datetime(df['Violation Time']).dt.time

C:\Users\hp\AppData\Local\Temp\ipykernel_8116\3994287525.py:1: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df['Violation Time'] = pd.to_datetime(df['Violation Time']).dt.time
C:\Users\hp\AppData\Local\Temp\ipykernel_8116\3994287525.py:1: FutureWarning: Parsed string "12:58 M" included an un-recognized timezone "M". Dropping unrecognized timezones is deprecated; in a future version this will raise. Instead pass the string without the timezone, then use .tz_localize to convert to a recognized timezone.
  df['Violation Time'] = pd.to_datetime(df['Violation Time']).dt.time
C:\Users\hp\AppData\Local\Temp\ipykernel_8116\3994287525.py:1: FutureWarning: Parsed string "10:22 M" included an un-recognized timezone "M". Dropping unrecognized timezones is deprecated; in a future version this will raise. Instead pass the string without the timezone, then use .tz_localize to convert to a recognized timezone.
  df['Violation Time'] = pd.to_datetime(df['Violation Time']).dt.time
C:\Users\hp\AppData\Local\Temp\ipykernel_8116\3994287525.py:1: FutureWarning: Parsed string "12:00 M" included an un-recognized timezone "M". Dropping unrecognized timezones is deprecated; in a future version this will raise. Instead pass the string without the timezone, then use .tz_localize to convert to a recognized timezone.
  df['Violation Time'] = pd.to_datetime(df['Violation Time']).dt.time

In [62]:
df.tail()

,Summons Number,Plate ID,Registration State,Plate Type,Issue Date,Violation Code,Vehicle Body Type,Vehicle Make,Issuing Agency,Street Code1,Street Code2,Street Code3,Vehicle Expiration Date,Violation Precinct,Issuer Precinct,Issuer Code,Violation Time,Violation County,Street Name,Date First Observed,Law Section,Sub Division,Vehicle Color,Vehicle Year,Feet From Curb,Violation Description,Issue Year,Issue Month
1293548,9002562561,24BJSW,FL,PAS,2022-07-26,74.0,SUBN,FORD,T,0.0,0.0,0.0,20221188.0,68.0,68.0,362237,07:32:00,K,Battery Ave,0.0,408.0,J2,BLACK,0.0,0.0,74A-Improperly Displayed Plate,2022,7
1293549,9002562573,24BJSW,FL,PAS,2022-07-26,14.0,SUBN,FORD,T,0.0,0.0,0.0,20221188.0,68.0,68.0,362237,07:34:00,K,Battery Ave,0.0,408.0,C,BLACK,0.0,0.0,14-No Standing,2022,7
1293550,9002562585,KSZ6687,NY,PAS,2022-07-26,40.0,SUBN,TOYOT,T,15880.0,0.0,0.0,20231229.0,68.0,68.0,362237,07:37:00,K,Battery Ave,0.0,408.0,E2,WH,2022.0,0.0,40-Fire Hydrant,2022,7
1293551,9002562597,HMV9474,NY,PAS,2022-07-26,21.0,4DSD,TOYOT,T,5580.0,10730.0,10780.0,20221223.0,68.0,68.0,362237,07:41:00,K,5th Ave,0.0,408.0,D1,GY,2016.0,0.0,21-No Parking (street clean),2022,7
1293552,9002562603,KVD5533,NY,PAS,2022-07-26,21.0,SUBN,HONDA,T,5580.0,10730.0,10780.0,20240307.0,68.0,68.0,362237,07:43:00,K,5th Ave,0.0,408.0,D1,GY,2004.0,0.0,21-No Parking (street clean),2022,7

In [68]:
df['Violation Time'].head(100)

0      10:37:00
1      10:45:00
2      11:16:00
3      10:52:00
4      11:07:00
7      12:05:00
8      17:35:00
9      15:07:00
10     14:25:00
11     15:20:00
12     11:02:00
13     18:06:00
14     12:50:00
15     10:31:00
16     11:32:00
17     11:35:00
18     18:07:00
19     19:12:00
20     14:35:00
21     13:56:00
23     18:26:00
24     20:41:00
25     18:13:00
26     09:40:00
27     11:51:00
28     12:21:00
29     12:20:00
30     15:50:00
31     09:22:00
32     14:14:00
33     04:30:00
35     04:40:00
36     04:45:00
37     04:49:00
40     12:48:00
42     17:37:00
44     19:44:00
46     14:22:00
47     10:23:00
48     10:30:00
49     12:23:00
50     11:09:00
51     08:32:00
52     09:02:00
53     09:50:00
55     13:00:00
56     16:34:00
57     16:30:00
58     04:53:00
59     16:55:00
60     10:45:00
62     09:15:00
63     09:51:00
65     20:41:00
66     21:58:00
67     02:39:00
68     03:06:00
71     11:25:00
72     12:35:00
73     14:05:00
74     12:15:00
75     11:50:00
76     14:00:00
77     20:09:00
78     22:30:00
79     23:02:00
80     14:42:00
81     14:42:00
82     20:40:00
83     01:39:00
85     22:53:00
86     16:52:00
87     17:20:00
88     14:35:00
89     12:05:00
91     00:38:00
92     07:17:00
93     02:55:00
96     22:42:00
97     16:31:00
98     20:12:00
101    14:45:00
102    18:40:00
103    10:17:00
104    10:24:00
105    10:57:00
106    18:54:00
107    19:30:00
109    08:37:00
110    09:20:00
111    01:10:00
112    22:18:00
113    22:14:00
114    10:38:00
115    11:50:00
116    16:17:00
117    16:52:00
118    16:26:00
119    16:39:00
120    17:11:00
Name: Violation Time, dtype: object

In [69]:
df['Violation Code'] = df['Violation Code'].astype(int)

In [70]:
df.dtypes

Summons Number                     object
Plate ID                           object
Registration State                 object
Plate Type                         object
Issue Date                 datetime64[ns]
Violation Code                      int32
Vehicle Body Type                  object
Vehicle Make                       object
Issuing Agency                     object
Street Code1                      float64
Street Code2                      float64
Street Code3                      float64
Vehicle Expiration Date           float64
Violation Precinct                float64
Issuer Precinct                   float64
Issuer Code                        object
Violation Time                     object
Violation County                   object
Street Name                        object
Date First Observed               float64
Law Section                       float64
Sub Division                       object
Vehicle Color                      object
Vehicle Year                      float64
Feet From Curb                    float64
Violation Description              object
Issue Year                          int32
Issue Month                         int32
dtype: object

In [77]:
# Filtered the 99 from Registration State as it is wrong type of Data contain
df = df[df['Registration State']!='99']